### ISSUE TITLE
allennlp.common.checks.ConfigurationError

### ISSUE THREAD

**Issue by cingtiye** [dki-lab/ArcaneQA#2]
Hi Yu,
Thank you very much for sharing ArcaneQA code.

When I run the code to predict grailqa datasets by the following shell, some errors occurred.

**Shell**
```bash
ROOT_DIR="/data1/Projects/ArcaneQA/"
cd ${ROOT_DIR}

PYTHONHASHSEED=23 python ${ROOT_DIR}source/run.py \
        predict \
        ${ROOT_DIR}saved_models/saved_models_coling/grail/model.tar.gz \
        ${ROOT_DIR}data/grailqa_v1.0_test_public.json \
        --include-package source.arcane \
        --include-package source.arcane_reader \
        --include-package source.utils.bert_interface \
        --include-package source.utils.my_pretrained_transformer_indexer \
        --include-package source.utils.my_pretrained_transformer_tokenizer \
        --use-dataset-reader \
        --predictor seq2seq \
        -c ${ROOT_DIR}configs/infer/grail_infer.json \
        --output-file ${ROOT_DIR}predictions/grail_arcane_dev.json \
        --cuda-device 0 \
        "$@"
```

**Error**
```shell
allennlp.common.checks.ConfigurationError: 'Cannot register my_pretrained_transformer as Tokenizer; name already in use for PretrainedTransformerTokenizer'
```

According to the error prompt, I deleted `--include-package source.utils.my_pretrained_transformer_tokenizer \`. Then the code could run.

Compared with the file `predictions/grail_arcane_dev_processed. json`, I found that the above code results were lower than that of your file. I evaluated the first 401 qid. My evaluation result was `EM=60.84, F1=69.72`, and yours (from `predictions/grail_arcane_dev_processed. json`) were `EM=71.82, F1=79.18`.  I observed bert-base-uncased model was directly loaded without being trained when I did predictions.

Thanks in advance for the help!

Best.

**Comment by entslscheia** [comment]
Hi,

You can avoid this error by `cd` into `source` and run
```
PYTHONPATH=../;PYTHONHASHSEED=23 python run.py \
 predict ../saved_models/saved_models_coling/grail/model.tar.gz \
 ../data/grailqa_v1.0_dev.json \
 --include-package arcane \
 --include-package arcane_reader \
 --include-package utils.bert_interface \
 --include-package utils.my_pretrained_transformer_indexer \
 --include-package utils.my_pretrained_transformer_tokenizer \
 --use-dataset-reader \
 --predictor seq2seq  \
 -c ../configs/infer/grail_infer.json \
 --output-file ../grail_arcane_dev.json
```
But it's fine to remove ` --include-package utils.my_pretrained_transformer_indexer` and `--include-package utils.my_pretrained_transformer_tokenizer`, since they are not actually used.

For the output file, have you executed the post-processing script (_i.e._, [process_predictions.py](https://github.com/dki-lab/ArcaneQA/blob/main/source/process_predictions.py))?

I've tested this repo before, and there was some very minor difference between the original predictions due to some changes in code cleaning / refactoring. The big difference observed by you is not expected, and there might be something wrong. Meanwhile, I am investigating the issue by re-running the prediction process by myself. I'll let you know what I find asap. Sorry about the inconvenience!

Best,
Yu

**Comment by entslscheia** [comment]
Hi @cingtiye,

I have re-run the experiments using this repo again, the results on dev set is as follows,
{'em': 0.69421854206713, 'f1': 0.7603328736012033, 'em_iid': 0.8625235404896422, 'f1_iid': 0.892891430399295, 'em_comp': 0.6578599735799208, 'f1_comp': 0.742176563320902, 'em_zero': 0.6359409190371991, 'f1_zero': 0.7100929591550909}, which is slightly worse than the original predictions but is comparable.

As I mentioned, the difference is due to some (unintentionally) changes during code cleaning / refactoring for code release (most likely resides in [this part](https://github.com/dki-lab/ArcaneQA/blob/94f258479bc843ec0dba44a0fa6861df9149ced7/source/arcane_reader.py#L151-L203)). I'll try to see whether I can entirely fix it. I also uploaded the reproduced predictions [here](https://github.com/dki-lab/ArcaneQA/blob/main/predictions/reproduce_grail_dev.json). You may check it out if you find it helpful.

Feel free to let me know if you need more help.
